import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { z } from 'zod';
import { useApp } from '../../contexts/AppContext';
const loginSchema=z.object({email:z.string().email(),password:z.string().min(8)}); type Login=z.infer<typeof loginSchema>;
export function LoginPage(){const {user,login}=useApp();const nav=useNavigate();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Login>({resolver:zodResolver(loginSchema),defaultValues:{email:'demo@wellora.app',password:'Demo123!'}});if(user)return <Navigate to="/dashboard" replace/>;return <AuthShell title="Welcome back" subtitle="Sign in to manage your family's health routines."><form className="space-y-4" onSubmit={handleSubmit(async v=>{await new Promise(r=>setTimeout(r,400));if(login(v.email,v.password)){toast.success('Signed in');nav('/dashboard')}else toast.error('Use the demo credentials shown below')})}><Field label="Email" error={errors.email?.message}><input className="input" type="email" {...register('email')}/></Field><Field label="Password" error={errors.password?.message}><input className="input" type="password" {...register('password')}/></Field><div className="flex items-center justify-between text-sm"><label className="flex gap-2"><input type="checkbox"/> Remember me</label><button type="button" className="text-brand-700">Forgot password?</button></div><button disabled={isSubmitting} className="btn-primary w-full">{isSubmitting?'Signing in…':'Sign in'}</button><div className="rounded-xl bg-brand-50 p-3 text-xs text-brand-900">Demo: demo@wellora.app / Demo123!</div><p className="text-center text-sm text-slate-500">New to Wellora? <Link to="/register" className="font-semibold text-brand-700">Create account</Link></p></form></AuthShell>}
const registerSchema=z.object({fullName:z.string().min(2),email:z.string().email(),password:z.string().min(8).regex(/[A-Z]/).regex(/[a-z]/).regex(/[0-9]/),confirm:z.string(),agree:z.literal(true)}).refine(v=>v.password===v.confirm,{path:['confirm'],message:'Passwords do not match'});type Register=z.infer<typeof registerSchema>;
export function RegisterPage(){const {user}=useApp();const nav=useNavigate();const {register,handleSubmit,formState:{errors}}=useForm<Register>({resolver:zodResolver(registerSchema)});if(user)return <Navigate to="/dashboard" replace/>;return <AuthShell title="Create your account" subtitle="Start organising medicines, periods, and family profiles."><form className="space-y-4" onSubmit={handleSubmit(()=>{toast.success('Mock account created. Use demo login.');nav('/login')})}><Field label="Full name" error={errors.fullName?.message}><input className="input" {...register('fullName')}/></Field><Field label="Email" error={errors.email?.message}><input className="input" type="email" {...register('email')}/></Field><Field label="Password" error={errors.password?.message}><input className="input" type="password" {...register('password')}/></Field><Field label="Confirm password" error={errors.confirm?.message}><input className="input" type="password" {...register('confirm')}/></Field><label className="flex gap-2 text-sm"><input type="checkbox" {...register('agree')}/> I agree to the terms and privacy notice.</label>{errors.agree&&<p className="text-xs text-red-600">Please agree before continuing.</p>}<button className="btn-primary w-full">Create account</button><p className="text-center text-sm text-slate-500">Already registered? <Link to="/login" className="font-semibold text-brand-700">Sign in</Link></p></form></AuthShell>}
function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="grid min-h-screen place-items-center bg-gradient-to-br from-brand-50 via-white to-rose-50 p-4"><div className="w-full max-w-md rounded-3xl border bg-white p-7 shadow-xl"><Link to="/" className="text-xl font-black text-brand-700">Wellora</Link><h1 className="mt-8 text-2xl font-bold">{title}</h1><p className="mb-6 mt-2 text-sm text-slate-500">{subtitle}</p>{children}</div></div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
